from .healthReq import HealthReq
from .userRegReq import UserRegReq
from .userLoginReq import UserLoginReq
from .userInfoReq import UserInfoReq
from .friendRequestReq import FriendRequestReq
from .friendListReq import FriendsListReq
from .createPostsReq import CreatePostsReq
from .sendMessageReq import SendMessageReq
from .getPostsReq import GetPostsReq
from .reportMessageReq import ReportMessageReq
